/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pa_23130628_proyecto_03;

import java.awt.Graphics;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fer Landa Santi
 */
public class PA_23130628_Frame_03 extends javax.swing.JFrame {

    /**
     * Creates new form PA_23130628_Frame_03
     */
    //Agregamos el Defaultablemodel para que muestre el Grid la tabla del Jframe
     private DefaultTableModel modelo;
    public PA_23130628_Frame_03() {
        initComponents();
        
        
        modelo = (DefaultTableModel) jTableInstrumentos.getModel();
        
        jTableInstrumentos.setShowGrid(true);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButMostrar = new javax.swing.JButton();
        jSpinInstrumento = new javax.swing.JSpinner();
        jButEjemplo = new javax.swing.JButton();
        jButDesfile = new javax.swing.JButton();
        jPanelDibujo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInstrumentos = new javax.swing.JTable();
        jButValores = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPanel = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jButDiagrama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButMostrar.setBackground(new java.awt.Color(204, 204, 255));
        jButMostrar.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jButMostrar.setText("Mostrar Instrumento");
        jButMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMostrarActionPerformed(evt);
            }
        });

        jSpinInstrumento.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jSpinInstrumento.setModel(new javax.swing.SpinnerNumberModel());

        jButEjemplo.setBackground(new java.awt.Color(204, 204, 204));
        jButEjemplo.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jButEjemplo.setText("Ejemplo");
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });

        jButDesfile.setBackground(new java.awt.Color(255, 204, 204));
        jButDesfile.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jButDesfile.setText("Desfile");
        jButDesfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDesfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDibujoLayout = new javax.swing.GroupLayout(jPanelDibujo);
        jPanelDibujo.setLayout(jPanelDibujoLayout);
        jPanelDibujoLayout.setHorizontalGroup(
            jPanelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        jPanelDibujoLayout.setVerticalGroup(
            jPanelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        jTableInstrumentos.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jTableInstrumentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Instrumento", "Marca", "Color", "Forma/Categoria", "Caracteristicas"
            }
        ));
        jTableInstrumentos.setRowHeight(25);
        jScrollPane1.setViewportView(jTableInstrumentos);

        jButValores.setBackground(new java.awt.Color(204, 255, 204));
        jButValores.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jButValores.setText("Crear Valores a los Objetos");
        jButValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButValoresActionPerformed(evt);
            }
        });

        jTextPanel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(jTextPanel);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_23130628_proyecto_03/Asignacion.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jButDiagrama.setBackground(new java.awt.Color(204, 204, 255));
        jButDiagrama.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jButDiagrama.setText("Diagrama");
        jButDiagrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDiagramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButEjemplo)
                                .addGap(18, 18, 18)
                                .addComponent(jButValores)
                                .addGap(40, 40, 40)
                                .addComponent(jButMostrar)
                                .addGap(32, 32, 32)
                                .addComponent(jSpinInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButDesfile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButDiagrama)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButMostrar)
                                .addComponent(jSpinInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButEjemplo)
                                .addComponent(jButDesfile)
                                .addComponent(jButValores))
                            .addComponent(jButDiagrama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMostrarActionPerformed
        // TODO add your handling code here:
        Graphics g = jPanelDibujo.getGraphics();
       // Hacemos un objeto de la clase graphics y que tome los elementos del JPanel
       //Creamos nuevos objetos de las clases de los instrumentos
        Clarinete c = new Clarinete();
        FlautadePan f = new FlautadePan();
         Bongo b = new Bongo();
         Pandereta p = new Pandereta();
        // Obtener el valor del spinner
        int valorSpinner = (int) jSpinInstrumento.getValue();
        // Realizar una acción basada en el valor del spinner
       
                if (valorSpinner > 4) {
                   //Si es mayor a 4 saltara un mensaje
                    JOptionPane.showMessageDialog(null, "Ya no hay mas instrumentos");
                } else {
                  //  Si es igual a cero saltara un mensaje
                    if(valorSpinner == 0){
                  JOptionPane.showMessageDialog(null, "Seleccione un instrumento");
                    }
                  else{ //Si no tengo valores en el JTable soltara un mensaje
                        if(jTableInstrumentos.getValueAt(1, 0) == null ){
                            JOptionPane.showMessageDialog(rootPane, "No tienes instrumentos");  }
                        else{
                            // Si es 1,2,3 o 4, Dibujara los respectivos dibujos con su descripcion o Atributos
                    if(valorSpinner == 1 ){
                        c.dibujar(g, jPanelDibujo);
                        jTextPanel.setText("Instrumento de Viento: Clarinete\nMarca: Yamaha\nColor: Negro\nForma: Conico\nCaracteristicas: Metalico");

                    }
                    else{
                        if(valorSpinner == 2 ){
                            f.dibujar(g, jPanelDibujo);
                            jTextPanel.setText("Instrumento de Viento: Flauta De Pan\nMarca: Jupiter\nColor: Cafe\nForma: Cilindrica\nCaracteristicas: Madera");
                        }
                        else{
                            if(valorSpinner == 3 ){
                                b.dibujar(g, jPanelDibujo);
                                jTextPanel.setText("Instrumento de Percusion: Bongo\nMarca: LP Matador\nColor: Rojo\nForma: Membranofono\nCaracteristicas: Set incompleto");
                            }
                            else{
                                if(valorSpinner == 4 ){
                                   p.dibujar(g, jPanelDibujo);
                                   jTextPanel.setText("Instrumento de Percusion: Pandereta\nMarca: Samba\nColor: Amarillo\nCategoria: Idiofono y Membranofono\nCaracteristicas:Madera");
                                    
                                }
                            }
                        }
                      }                                       
                    }
                    
                    }
                    }
                    
    }//GEN-LAST:event_jButMostrarActionPerformed

    private void jButDesfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDesfileActionPerformed
        // TODO add your handling code here:
        Graphics g = jPanelDibujo.getGraphics();
        //Creamos un objeto de la clase Graphics
        //Creamos objetos de las clases de los instrumentos
        //Los metemos a un ciclo que sera las veces que seran dibujados y luego llamamos el metodo de mover
        
        Pandereta p = new Pandereta();
        jTextPanel.setText("Instrumento de Percusion: Pandereta\nMarca: Samba\nColor: Amarillo\nCategoria: Idiofono y Membranofono\nCaracteristicas:Madera");
        for(int i = 1; i<=300;i++){
        p.mover(g, jPanelDibujo,  i,  i);
        }
        
        
        FlautadePan f = new FlautadePan();
        jTextPanel.setText("Instrumento de Viento: Flauta De Pan\nMarca: Jupiter\nColor: Cafe\nForma: Cilindrica\nCaracteristicas: Madera");
        for(int i = 1; i<=300;i++){
        f.mover(g, jPanelDibujo,  i,  i);
        }
        
        
        Clarinete c = new Clarinete();
        jTextPanel.setText("Instrumento de Viento: Clarinete\nMarca: Yamaha\nColor: Negro\nForma: Conico\nCaracteristicas: Metalico");
        for(int i = 1; i<=300;i++){
            c.mover(g, jPanelDibujo,  i,  i);
        }
        
        
        Bongo b = new Bongo();
        jTextPanel.setText("Instrumento de Percusion: Bongo\nMarca: LP Matador\nColor: Rojo\nForma: Membranofono\nCaracteristicas: Set incompleto");
        for(int i = 1; i<=300;i++){
        b.mover(g, jPanelDibujo,  i,  i);
        }
        

        
        
    }//GEN-LAST:event_jButDesfileActionPerformed

    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        // TODO add your handling code here:
        //Ponemos el DefaultTableModel para trabajar de una manera mas sencilla
        DefaultTableModel mod = (DefaultTableModel)jTableInstrumentos.getModel();
        modelo.setRowCount(4);
        //Aqui unos arreglos que guardaran los valores del Jtable
        // Este guarda el nombre de las clases
        String[] clases = {"Viento:Clarinete","Viento:Flauta de Pan", "Percusion:Bongo","Percusion:Pandereta"};
        
        //Aqui guardaremos los valores
        String[] marcas = {"Yamaha","Jupiter","LP Matador", "Samba"};
        String[] colores = {"Negro","Cafe","Rojo","Amarillo"};
        String[] forma_Categoria = {"Cilindrico", "Conico", "Membranofono", "Idiofono y Membranofono"};
        String[] caracteristicas = {"Madera", "Metalico", "Set incompleto", "Madera"};
        
        //En este for hacemos que se ingrecen los nuevos valores al JTable
        for(int r = 0;r < 4;r++){
            mod.setValueAt(clases[r], r, 0);
            mod.setValueAt(marcas[r], r, 1);
            mod.setValueAt(colores[r], r, 2);
            mod.setValueAt(forma_Categoria[r], r, 3);
            mod.setValueAt(caracteristicas[r], r, 4);
                    
            
        }
        
        
        
    }//GEN-LAST:event_jButEjemploActionPerformed

    private void jButValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButValoresActionPerformed
        // TODO add your handling code here:
        
        //Aqui a los objetos nuevo les agregamos los valores del jTable a sus atributos
        //Flauta
        FlautadePan fla = new FlautadePan();
        fla.setMarca(jTableInstrumentos.getValueAt(0, 1)+"");
        fla.setColor(jTableInstrumentos.getValueAt(0, 2)+"");
        fla.setForma(jTableInstrumentos.getValueAt(0, 3)+"");
        fla.setCaracteristica(jTableInstrumentos.getValueAt(0, 4)+"");      
      
        //Clarinete
        Clarinete cla = new Clarinete();
        cla.setMarca(jTableInstrumentos.getValueAt(1, 1)+"");
        cla.setColor(jTableInstrumentos.getValueAt(1, 2)+"");
        cla.setForma(jTableInstrumentos.getValueAt(1, 3)+"");
        cla.setCaracteristica(jTableInstrumentos.getValueAt(1, 4)+"");
        
        //Bongo
        Bongo bon = new Bongo();
        bon.setMarca(jTableInstrumentos.getValueAt(2, 1)+"");
        bon.setColor(jTableInstrumentos.getValueAt(2, 2)+"");
        bon.setCategoria(jTableInstrumentos.getValueAt(2, 3)+"");
        bon.setCaracteristica(jTableInstrumentos.getValueAt(2, 4)+"");
        
        //Pandereta
        Pandereta pan = new Pandereta();
        pan.setMarca(jTableInstrumentos.getValueAt(3, 1)+"");
        pan.setColor(jTableInstrumentos.getValueAt(3, 2)+"");
        pan.setCategoria(jTableInstrumentos.getValueAt(3, 3)+"");
        pan.setCaracteristica(jTableInstrumentos.getValueAt(3, 4)+"");
        
        // Usando el DefaultTable los vamos a ordenar
                DefaultTableModel mod = (DefaultTableModel) jTableInstrumentos.getModel();
// Ordenamiento de burbuja por color
for (int i = 0; i < mod.getRowCount() - 1; i++) {
    for (int j = 0; j < mod.getRowCount() - i - 1; j++) {
        String color1 = (String) mod.getValueAt(j, 2); // Columna de color
        String color2 = (String) mod.getValueAt(j + 1, 2); // Columna de color del siguiente elemento
        
        // Comparar los colores ignorando mayúsculas/minúsculas
        if (color1.compareToIgnoreCase(color2) > 0) {
            // Intercambiar las filas si el color actual es mayor que el siguiente
            for (int k = 0; k < mod.getColumnCount(); k++) {
                Object temp = mod.getValueAt(j, k);
                mod.setValueAt(mod.getValueAt(j + 1, k), j, k);
                mod.setValueAt(temp, j + 1, k);
            }
        }
    }
}

// Actualizar el JTable con los objetos ordenados por color
jTableInstrumentos.setModel(mod);


        
        JOptionPane.showMessageDialog(rootPane, "Objetos Creados Con Exito!");
        
    }//GEN-LAST:event_jButValoresActionPerformed

    private void jButDiagramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDiagramaActionPerformed
        // TODO add your handling code here:
        //Abrimos un nuevo Frame
         jButDiagrama.addActionListener(e -> {
            PA_23130628_Frame_03a segundoFrame = new PA_23130628_Frame_03a();
            segundoFrame.setVisible(true);
        });
    }//GEN-LAST:event_jButDiagramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_23130628_Frame_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_23130628_Frame_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_23130628_Frame_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_23130628_Frame_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_23130628_Frame_03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButDesfile;
    private javax.swing.JButton jButDiagrama;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JButton jButMostrar;
    private javax.swing.JButton jButValores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelDibujo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinInstrumento;
    private javax.swing.JTable jTableInstrumentos;
    private javax.swing.JTextPane jTextPanel;
    // End of variables declaration//GEN-END:variables
}
